development:
    :address: smtp.gmail.com
    :port: 587
    :authentication: plain
    :user_name: jpearson556@gmail.com
    :password: C12D3477
    :enable_starttls_auto: true
Production:
    :address: smtp.gmail.com
    :port: 587
    :authentication: plain
    :user_name: jpearson556@gmail.com
    :password: C12D3477
    :enable_starttls_auto: true